<?php

define( 'TEMP', '.' );
define( 'CONFIG', '.' );
define( 'DATA', '.' );
define( 'DISPLAY_ERRORS', '0' );
define( 'ERROR_REPORTING', E_ERROR );
define( 'DEV_MODE', false );
define( 'TEST_MODE', false );

define( 'SAP_USER', 'username' );
define( 'SAP_PWD', 'password' );
define( 'SAP_URL', 'https' );

define( 'TEQUILA_URL', 'https' );
define( 'TEQUILA_TIMEOUT', 0 );
define( 'APP_NAME', 'app' );
define( 'APP_URL', '' );
define( 'TEQUILA_LANGUAGE', 0 );
define( 'TEQUILA_REQUEST', ['uniqueid'] );
define( 'TEQUILA_ALLOWS', '' );
define( 'TEQUILA_REQUIRED', '' );
define( 'COOKIE_NAME', '' );
define( 'SESSION_KEY', '' );
define( 'SESSION_USER', '' );
define( 'SESSION_CREATION', '' );
