<?php

define( 'TEMP', '.' );
define( 'CONFIG', '.' );
define( 'DATA', '.' );
define( 'DISPLAY_ERRORS', '0' );
define( 'ERROR_REPORTING', E_ERROR );
define( 'DEV_MODE', false );
define( 'TEST_MODE', false );

define( 'SAP_USER', 'username' );
define( 'SAP_PWD', 'password' );
define( 'SAP_URL', 'https' );

define( 'TEQUILA_URL', 'https' );
define( 'TEQUILA_TIMEOUT', 0 );
define( 'APP_NAME', 'App' );
define( 'APP_URL', '' );
define( 'TEQUILA_LANGUAGE', 1 );
define( 'TEQUILA_REQUEST', '' );
define( 'TEQUILA_ALLOWS', '' );
define( 'TEQUILA_REQUIRED', '' );
define( 'COOKIE_NAME', 'cookie' );
define( 'SESSION_KEY', 'key' );
define( 'SESSION_USER', 'user' );
define( 'SESSION_CREATION', 'creation' );
