<div class="modal fade" id="info-modal" tabindex="-1" role="dialog" aria-labelledby="info-modal-title" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" id="info-modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="file-modal-title">Titre</h5>
                    <button type="button" class="close info-ok" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
            </div>
            <div class="modal-body" id="file-modal-body">
                Body
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary info-ok">OK</button>
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="error-modal" tabindex="-1" role="dialog" aria-labelledby="error-modal-title" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" id="error-modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="wrong-modal-title">Problème de consistance</h5>
                    <button type="button" class="close" id="error-modal-cancel" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
            </div>
            <div class="modal-body" id="wrong-modal-body">
                Body
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" id="error-modal-correct">Corriger</button>
                <button type="button" class="btn btn-primary" id="error-modal-save">Sauver</button>
            </div>
        </div>
    </div>
</div>
