<div id="tables-message"></div>
<div id="tables-desktop">
    <div id="tables-top">
        <div id="tables-left">
            <div class="tables-column">
                <label class="tile mini-tile" for="tables-import">
                    <input id="tables-import" type="file" name="tables-import" class="zip-file lockable" accept=".zip" />
                    Importer
                </label>
                <div id="tables-read" class="tile mini-tile">Lire</div>
                <div id="tables-create" class="tile mini-tile">Créer</div>
            </div>
        </div>
        <div id="tables-center">
            <div id="tables-dates"></div>
            <div id="tables-files"></div>
        </div>
        <div id="tables-right">
            <div class="tables-column">
                <div id="tables-load" class="tile mini-tile desactived-tile">Ecrire</div>
                <div id="tables-remove" class="tile mini-tile">Effacer</div>
            </div>
        </div>
    </div>
    <div id="tables-sub"></div>
    <div id="tables-bottom">
        <div id="tables-cancel" class="tile mini-tile desactived-tile">Annuler</div>
        <div id="tables-save" class="tile mini-tile desactived-tile">Sauvegarder</div>
        <div id="tables-check" class="tile mini-tile desactived-tile">Vérifier</div>
    </div>
</div>
<div id="tables-editor"></div>
