
<link rel="stylesheet" href="css/jquery-ui.min.css">
<script src="js/jquery-ui.min.js"></script>
<script src="js/jszip.min.js"></script>
<script src="js/papaparse.min.js"></script>
<script src="js/tables/tables.js" type="module"></script>
<script src="js/tables/tables-editor.js" type="module"></script>
<script src="js/tables/tables-tests.js" type="module"></script>
<script src="js/tables/tables-dates.js" type="module"></script>
<script src="js/tables/file-tests.js" type="module"></script>
